name: sse_channel
description: StreamChannel wrappers for Server Sent Events.
version: 0.0.4
repository: https://www.github.com/jamiewest/sse_channel

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  async: ^2.10.0
  http: ^1.1.0
  pool: ^1.5.1
  sse: ^4.1.1
  stream_channel: ^2.1.1
  uuid: ^4.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0


